package com.learning.test.exceptionhandling;

public class ThrowExcepExample {
	
	
    static int age=13;   
	
	public  void test() throws ArrayIndexOutOfBoundsException,ArithmeticException {  
		
//		try {
		//int userid=getUserInfo();
		//1
//		catch(E)
		//
		//  user information //db operation here based on userid  //DataAccessException|InvalidDataException
//		throw new ArrayIndexOutOfBoundsException("Data not found in DB");
		//service layer - business logic - Arithemtci ex/ArrayInedex
//		throw new ArithmeticException("ArithmeticException in Businnes");
		//
		//
		//
//		}catch(Exception e) {
//			System.out.println();
//		}
		
	
		
		
		
//		if(age<18)  
//			throw new ArithmeticException("not validone");  
//		else  
//			System.out.println("welcome to vote"); 
//		
//		
	}  
}

//	try {
//	ThrowExcepExample e = new ThrowExcepExample();
//	e.test();
//	}catch(Exception e){
//		System.out.println(e.getMessage());
//	}
//	}
	
	
	
	
	
	
	
	
	
	
	
	
	
	